### ISSUE TITLE
Bug/Cosmetic error : On page for 2026 dates the title is 2025

### ISSUE THREAD

**Issue by RajatM24** [kewonit/Timekeeper#30]
![Screenshot_20240701-173321_Brave.jpg](https://github.com/kewonit/Timekeeper/assets/172014613/ee49543e-d994-4d36-b39a-f14e2500f204)

And yeah maybe add an last update sort of time so that the user can check if the the validity of data

**Comment by kewonit** [comment]
Yep, thanks for the suggestion, I will add a changelog with the next update! Also fix up this UI

**Comment by kewonit** [comment]
https://github.com/kewonit/Timekeeper/commit/b3722db4cec62de06473a3e33b37a86999520e57

Fixes the issue, changelog will be introduced in the next update, along with global variables for the dates of these examinations, so they are easier to edit and manage, also easier to update using PR send by the community! 

Thanks
